<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.mountainbackend</groupId>
	<artifactId>pedidos360-backend-parte2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>pedidos360-backend-parte2</name>
	<description>Pedidos360 - Microservicios backend parte 2 (Notificaciones + Carrito + Envíos, EC2 backend-2)</description>

	<modules>
		<module>servicio-notificaciones</module>
		<module>servicio-carrito</module>
		<module>servicio-envios</module>
	</modules>

	<properties>
		<java.version>17</java.version>
	</properties>
</project>
